InternetMaximalism/intmax.js

.github/workflows/build-test.yml, package-lock.json, package.json, src/utils/merkle-tree.ts, test/utils/merkle-tree.test.ts
replace sha3 hash func into neptune
=> fix npm neptune build test

.github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build-test.yml
I added pr template and tested only node version 16 environment.
=> feat: pr template

src/utils/merkle-tree.ts, test/utils/merkle-tree.test.ts
=> Fix test description

src/utils/converter.ts, src/utils/index.ts, src/utils/sparse-merkle-tree.ts, test/utils/merkle-tree.test.ts, test/utils/sparse-merkle-tree.test.ts, tsconfig.json, types/index.d.ts
implement smt wrapper to get proof.
=> implement wrapper smt

package-lock.json, package.json, src/utils/database.ts, src/utils/detect.ts, src/utils/index.ts, types/index.d.ts
create wrapper indexeddb class
=> create indexeddb wrapper class for state management

src/utils/sparse-merkle-tree.ts, test/utils/sparse-merkle-tree.test.ts, tsconfig.json
- get found and foundValue when you get the proof.
=> feat: get proof with each keys

src/utils/sparse-merkle-tree.ts, test/utils/sparse-merkle-tree.test.ts
- insert multiple node into smt
=> insert multiple data to smt

src/index.ts, src/state/index.ts, src/state/user-state.ts, src/utils/database.ts, test/state/user-state.test.ts, test/utils/database.test.ts
get diff from the server and merge it to the user state tree.
=> merge diff and change user state

LICENSE, package.json
changed GPL-3.0 LICENSE from MIT.
=> changed gpl

package-lock.json, package.json, src/index.ts, src/transaction/index.ts, src/transaction/transaction.ts, src/utils/converter.ts, src/utils/sparse-merkle-tree.ts, test/transaction/transaction.test.ts, tsconfig.json, types/index.d.ts
- sign a transaction with max length of 192
=> sign a transaction

src/account/account.ts, src/utils/web3-client.ts
=> ethereum type is external provider

README.md, package-lock.json, package.json
=> run prebuild

package-lock.json, package.json, src/account/account.ts, src/utils/web3-client.ts, test/account/account.test.ts
pass provider to initialize web3 client
=> pass provider to initialize web3 client

src/utils/converter.ts, src/utils/sparse-merkle-tree.ts, test/utils/sparse-merkle-tree.test.ts
=> checked proof and root value

src/utils/sparse-merkle-tree.ts, test/utils/sparse-merkle-tree.test.ts
=> test smt proof response

package-lock.json, package.json
- update circomlibjs for sign poseidon
=> update circomlibjs for sign poseidon

package-lock.json, package.json
=> fixed signposeidon buf slice

package-lock.json, package.json, src/state/user-state.ts, src/utils/converter.ts, src/utils/merkle-tree.ts
define util types and version v0.1.2
=> define types and version v0.1.2

package-lock.json, package.json, src/account/account.ts, src/utils/web3-client.ts
- pass the provider only
- detect whether is metamask or not
- changed the sign msg
=> pass the web3 provider and changed sign msg

src/account/account.ts, src/index.ts, src/interface/index.ts, src/transaction/transaction.ts, src/utils/web3-client.ts, test/account/account.test.ts, test/transaction/transaction.test.ts
- get eddsa from memory
- activate the web3 client
=> get eddsa from memory

src/account/account.ts, src/config.ts, src/index.ts, src/interfaces/account.ts, src/interfaces/index.ts, src/interfaces/transaction.ts, src/transaction/transaction.ts, src/utils/web3-client.ts
- use configuration
- define types on inteface files
=> use configuration

package-lock.json, package.json, src/account/account.ts, src/interfaces/account.ts, src/interfaces/index.ts, src/state/user-state.ts, src/utils/crypto-hash.ts, types/index.d.ts
=> added eddsa type

src/account/account.ts, src/interfaces/account.ts, src/interfaces/index.ts, src/interfaces/transaction.ts, src/transaction/transaction.ts, src/utils/web3-client.ts, test/account/account.test.ts, test/transaction/transaction.test.ts
=> feat: send signed tx

src/account/account.ts, src/interfaces/account.ts, src/interfaces/index.ts, src/interfaces/transaction.ts, src/transaction/transaction.ts, src/utils/merkle-tree.ts, src/utils/web3-client.ts, test/account/account.test.ts, test/transaction/transaction.test.ts, test/utils/merkle-tree.test.ts
=> Added merkletree test

src/account/account.ts, src/interfaces/account.ts, src/interfaces/transaction.ts, src/transaction/transaction.ts, src/utils/converter.ts, test/account/account.test.ts, test/hash/poseidon.test.ts, test/transaction/transaction.test.ts, types/index.d.ts
=> Fix signed transaction
